config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :goods do
    resources :reviews
  end
  root 'goods#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :goods
end

app/models/good.rb
class Good < ActiveRecord::Base
belongs_to :user
belongs_to :category
has_many :reviews

has_attached_file :good_img, styles: { good_index: "250x350>", good_show: "325x475>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :good_img, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :good
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :goods
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :find_good, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

def index
  if params[:category].blank?
  @goods = Good.all.order ("created_at DESC")
  else
    @category_id = Category.find_by(name: params[:category]).id
    @goods = Good.where(:category_id => @category_id).order ("created_at DESC")
    end
end

  def show
  end

  def new
    @good = current_user.goods.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @good = current_user.goods.build(good_params)
    @good.category_id = params[:category_id]

    if @good.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @categories = Category.all.map{ |c| [c.name, c.id] }
    if @good.update(good_params)
      redirect_to good_path(@good)
    else
      render 'edit'
    end
  end

  def destroy
    @good.destroy
    redirect_to root_path
  end

  private
def good_params
  params.require(:good).permit(:title, :description, :other, :category_id, :good_img)
end


def find_good
  @good = Good.find(params[:id])
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_good
    before_action :find_review, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]

    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.good_id = @good.id
        @review.user_id = current_user.id
    
    if @review.save
        redirect_to good_path(@good)
    else
        render 'new'
    end
    end

    def edit
    end

    def update

      if @review.update(review_params)
          redirect_to good_path(@good)
      else
        render 'edit'
      end
    end

    def destroy
      @review.destroy
      redirect_to good_path(@good)
    end

private
    def review_params
    params.require(:review).permit(:rating, :comment)
    end

    def find_good
    @good = Good.find(params[:good_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/goods/_form.html.erb
<%= simple_form_for @good, :html => { :multipart => true } do |f| %>
<%= select_tag(:category_id, options_for_select(@categories), :prompt => "type overtreding") %>
<%= f.file_field :good_img %>
<%= f.input :title, label: "Naam item" %>
<%= f.input :description, label: "Omschrijving" %>
<%= f.input :other, label: "Andere info" %>
<%= f.button :submit, "Toevoegen", :class => 'btn-custom2' %>

<% end %>

app/views/goods/edit.html.erb
<div class="col-md-6 col-md-offset-3">
    
    <div class="edit-good-form">
<h1> Item aanpassen </h1>
<%= simple_form_for @good, :html => { :multipart => true } do |f| %>
    <%= f.select :category_id, @categories %>
    <%= f.file_field :good_img %>
    <%= f.input :title, label: "Naam item" %>
    <%= f.input :description, label: "Omschrijving" %>
    <%= f.input :other, label: "Andere info" %>
<%= f.button :submit, "Aanpassen", :class => 'btn-custom2' %>
<% end %>
    </div>

app/views/goods/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @goods.count == 0 %>
    <h4>Nog geen overtredingen van dit type beschikbaar.</h4>

    <% else %>
        
        <div class="row">

    <% @goods.each do |good| %>
    
    <div class="col-md-3">
      <h5><center> <%= link_to good.title, good_path(good) %> </center></h5>
      <a href="/goods/<%= good.id %>">

        <%= image_tag good.good_img.url(:good_index), class: "good" %>

        </a>
        </div>
    
    <% end %>
    </div>
<% end %>

app/views/goods/new.html.erb
<div class="col-md-6 col-md-offset-3">
    
    <div class="new-good-form">
<h1>Nieuw item toevoegen</h1>

<%= render 'form' %>
    </div>
</div>

app/views/goods/show.html.erb
<div class="row">

<div class="col-md-4">
 
<%= image_tag @good.good_img.url(:good_show), class: "good-show" %>
</div>


<div class="col-md-8">
  <div class="good-info">
<h2 class="good.title"><%= @good.title %></h2>
<h4 class="overtreding">Type overtreding: <%= @good.category.name %></h4>
<h4 class="ambtenaar">Vaststellend ambtenaar: <%= @good.user_id %></h4>
<h4 class="andere"><%= @good.other %></h4>
<p class="omschrijving"><%= @good.description %></p>
</div>
</div>

</div>
 <p></p>
<div class="row">
<div class="col-md-4">
<div class="links btn-group">


<% if user_signed_in? %>

        <% if @good.user_id == current_user.id %>
    
        <%=link_to "Wijzig", edit_good_path(@good), class: "btn btn-custom" %>
        <%=link_to "Verwijder", good_path(@good), method: :delete, data: { confirm: "Ben je zeker?" } , class: "btn btn-custom" %>
    
    <% end %>
    
<% end %>

</div>
<div class="reviews" >
  <h1>Opmerkingen</h1>
  <%= render @good.reviews %>
        
        <div>
      
            <%= link_to "Opmerking toevoegen", new_good_review_path(@good), class: "btn btn-custom" %>
                
        </div>
</div>
</div>
        
        
        
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goodsreview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default">


  <div class="container">
    <div class="navbar-header">
      <%= link_to "Goederenoverzicht", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
      <li><%=link_to "Afmelden", destroy_user_session_path, method: :delete %> </li>
          <% else %>
          <li><%=link_to "Inloggen", new_user_session_path %></li>
      <%end%>
    </ul>


    <ul class="nav navbar-nav navbar-right">

      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
        Type overtreding<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, goods_path(category: category.name), class: "link" %>

              </li>
          <%end%>
        </ul>


    </li>


      <% if user_signed_in? %>
          <li><%=link_to "Item toevoegen", new_good_path %></li>
          <%end%>
          </ul>

  </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@good, @good.reviews.build]) do |f| %>
<%= f.input :comment %>
<%= f.button :submit, "Toevoegen",  :class => 'btn-custom2' %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review">

<p><%= review.rating %></p>
<p class="review-comment"><%= review.comment %></p>

<% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
        
<div class="links btn-groups">
<%= link_to "Wijzig", edit_good_review_path(review.good, review), class: "btn btn-custom" %>
<%= link_to "Verwijderen", good_review_path(review.good, review), method: :delete, data: { confirm: "Ben je zeker?" }, class: "btn btn-custom" %>
</div>
<% end %>
<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
    
    <div class="edit-review-form">
<h1>Commentaar aanpassen</h1>

<%= simple_form_for([@good, @review]) do |f| %>
<%= f.input :comment %>
<%= f.button :submit, "Aanpassen",  :class => 'btn-custom2' %>

<% end %>
</div>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
    
    <div class="edit-good-form">
<h1>Nieuwe opmerking toevoegen</h1>

<%= render 'form' %>
    </div>